### ISSUE TITLE
[Dot] dot complains: trouble in init_rank

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#681]
Ported Issue from Mantis
Original ID: 1834
Reported By: Kevin Hunter

SEVERITY: MINOR
Submitted: 2010-03-09 05:24:50

OS: X86-LINUX-UBUNTU KARMIC

VERSION: 2.20.2

DESCRIPTION
-----------

<br>

I'm guessing that too many subgraph parts makes Graphviz confused.
<br>

`$ dot -T pdf PokerParty_4Men4Women.dot > PokerParty_4Men4Women.pdf`
 ... produces "Error: trouble in init_rank", then lots of information [attached]
<br>

Some perhaps pertinent info:
<CD>
```
$ dot -V
dot - Graphviz version 2.20.2 (Wed Sep 16 11:12:21 UTC 2009)
```
<br>

```
$ uname -a
Linux hani 2.6.31-19-generic #56-Ubuntu SMP Thu Jan 28 02:39:34 UTC 2010 x86_64 GNU/Linux

```<br>

```
$ lsb_release -a
No LSB modules are available.
Distributor ID-	Ubuntu
Description-	Ubuntu 9.10
Release-	9.10
Codename-	karmic
```
</CD>

**Comment by GadgetSteve** [comment]
Marked as fixed in git log so closing.

**Comment by haitaoyao** [comment]
@GadgetSteve  I compiled the latest master branch and still got the same error. I think the bug still exists. thanks

```
Error: trouble in init_rank
    %0 26
    %0 2
    %0 2
    %0 6
    %0 11
    %0 2
    %0 5
    %0 6
    %0 18
    %0 6
    %0 24
    %0 2
    %0 11
    %0 2
    %0 10
```

**Comment by magneticnorth** [comment]
As a workaround, please can you try -Gnewrank=true  ?
Is there a gist or other place that contains the file that triggers the bug?

**Comment by haitaoyao** [comment]
sorry, I can not provide the dot file. And I'm using the python library named `graphviz` to generate the dot file. It has 108 edges and 86 nodes inside  33 subgraphs .

**Comment by emden** [comment]
There is whole number of paths that cause this problem. (It is probably the oldest Graphviz bug still not fully resolved.) I cleaned up a few of them a couple of years ago, but I know there are more. Obviously, without having a input causing the problem limits what we can do. Why can't you provide the graph? If it's proprietary, you can anonymize it.

**Comment by GadgetSteve** [comment]
@emden - Should I re-open this or leave it closed until @haitaoyao, or someone, can provide a test case dot file?

**Comment by emden** [comment]
This can probably be marked as a duplicate of the many other bug reports concerning the same problem.

**Comment by magneticnorth** [comment]
I would like to take a fresh look at this.  (Last night as I was, finally, unpacking and
discarding a lot of stuff from AT&T, I found a copy of Chvatal’s book, that comments
on network simplex algorithms and issues in avoiding cycling and other degeneracies,
that bears closer scrutiny. Weird coincidence.)

I tried to find Gadget Steve’s test file in github along with the issue that was filed but
I must not be seeing it.

**Comment by emden** [comment]
I don't how the converter from mantis to github handles the related files. Anyway, http://www.graphviz.org/bugs/b1900.dot (in http://www.graphviz.org/mantisbt/view.php?id=1834)

**Comment by GadgetSteve** [comment]
@magneticnorth - I ported the tickets from the Mantis Ticket DB No. 1834 - the original ticket was raised by Kevin Hunter and any attachments will still be in the Mantis DB.  The XML dump of the open tickets did not include any referenced files. I did take a look at the raw data for this ticket and it referenced PokerParty_4Men4Women.dot but there is no actual file or link in the file that I have.

**Comment by GadgetSteve** [comment]
I tried to cut the failing file down a bit and got to the point where it is on the edge of failing.
Just before the file fails completely there is a message: Warning: Unable to reclaim box space in spline routing for edge "M1 Q W1,M1,W1,M1" -> "M1 Q W1,M1,W1,M2". Something is probably seriously wrong.

If it is any help the borderline file, which will crash on Win Graphviz2.38 as it is but can survive with a couple of items commented out is attached. (Of course it might be platform dependent)

[b1900a.zip](https://github.com/ellson/graphviz/files/409740/b1900a.zip)

.

**Comment by magneticnorth** [comment]
Thanks.  I thought the problem was the classic “trouble in init_rank” though, not spline routing infeasibility.

**Comment by ens-lg4** [comment]
This may or may not be the same issue:
    https://github.com/ellson/graphviz/issues/1173

**Comment by maxfiedler** [comment]
I am getting a similar error code
`PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 203, in restore_settings
    self._refresh_rosgraph()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 227, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 254, in _generate_dotcode
    quiet=quiet)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 579, in generate_dotcode
    dotcode = dotcode_factory.create_dot(dotgraph)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_dotgraph/pydotfactory.py", line 163, in create_dot
    dot = graph.create_dot()
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1735, in <lambda>
    lambda f=frmt, prog=self.prog: self.create(format=f, prog=prog)
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1961, in create
    status, stderr_output))
InvocationException: Program terminated with status: 1. stderr follows: Error: trouble in init_rank
	%0 2
	%0 10
	%0 4
	%0 8
	%0 1
	%0 1
	n__pose_estimation_preprocessing_autonomos_pointcloud_filters_normals_generator 3
	%0 2
	n__pose_estimation_preprocessing_kragen_crop_box 2
	%0 1
	n__pose_estimation_preprocessing_autonomos_voxel_grid 1
	%0 1
	n__pose_estimation_preprocessing_container_crop_box 1
	%0 1
	n__pose_estimation_preprocessing_autonomos_throttle 1
	n__pose_estimation_autonomos_pose_frame_transformer_ground_to_bin 1
	%0 1
	%0 1
	%0 1
	n__pose_estimation_autonomos_z_offset_corrector 1
	%0 1
	%0 1
	%0 1
	n__pose_estimation_autonomos_pose_frame_transformer_bin_to_ground 1
	n__pose_estimation_autonomos_initial_pose_estimator 1
	%0 1
	%0 2
	%0 1
	%0 1
	color 1
	n__pose_estimation_autonomos_icp_pose_estimator 1
	%0 1
	%0 2
	%0 2
	%0 2
	%0 2
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
libpath/shortest.c:324: triangulation failed
libpath/shortest.c:207: cannot find triangle path
Warning: Unable to reclaim box space in spline routing for edge "n__pose_estimation_preprocessing_autonomos_pointcloud_filters_normals_generator" -> "n__pose_estimation_autonomos_initial_pose_estimator". Something is probably seriously wrong.
`

Unfortunately I am also not allowed to share the code or the graph. But, I can share the info that the issue only arises when I use nodelets. If I use nodes instead, the error does not show

**Comment by hanjoosten** [comment]
I run into this bug, and noticed there was a need for some sample file. Maybe this (programatically generated) file can help? 
[ExampleForGraphvizIssue681.txt](https://github.com/ellson/graphviz/files/706860/ExampleForGraphvizIssue681.txt)

**Comment by jkufner** [comment]
> As a workaround, please can you try -Gnewrank=true ?

I have the same problem and this workaround makes Graphviz crash in different way, but it stil cannot render my graph.

**Comment by jkufner** [comment]
Every tiny change in the dot file causes the bug to disappear or appear. Even things like removing text from a tooltip, which does not make sense to me at all. Or changing output from SVG to PNG...

**Comment by magneticnorth** [comment]
Greetings.  Since the init_rank() code was rewritten 5 or 6 weeks ago, are you
still having this problem?  I tried ExampleForGraphvizIssue681.txt  both with
and without -Gnewrank=true  and did not encounter any runtime errors.

$ dot -V
dot - graphviz version 2.41.20170119.0508 (20170119.0508)
$ dot ExampleForGraphvizIssue681.txt -o /dev/null
$ dot -Gnewrank=true ExampleForGraphvizIssue681.txt -o /dev/null
$

**Comment by hanjoosten** [comment]
Hi magneticnorth, thanks for looking into this issue. I used the latest current stable release on a windows machine: version 2.38. I see that you use 2.41. 
2.38 is more than 5 or 6 weeks old.

**Comment by ErwinJanssen** [comment]
The most recent version can be compiled on Windows, that way you can benefit from the fix. We are working on a new binary release for Windows, but building from source is the only to use a more recent version than 2.38 on Windows way for now.

**Comment by emden** [comment]
*2.38 is more than 5 or 6 weeks old.*
Now there is an understatement. :)

**Comment by hanjoosten** [comment]
Any idea when this is released? Even if I would compile the dev version myself, the users of my software need a stable version of graphviz. 
And is there a link to a discription how to compile?

**Comment by lewellyn** [comment]
http://graphviz.org/doc/winbuild.html has some build notes for the Windows versions. :)
