### ISSUE TITLE
[Dot] segfault in cluster.c

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#919]
Ported Issue from Mantis
Original ID: 1149
Reported By: Jose Carlos Bins Filho

SEVERITY: MINOR
Submitted: 2006-07-10 12:28:05

OS: _-_-

VERSION: 2.9.20060710.0440-1
## DESCRIPTION

<br>

<CD>
[This problem was reported on graphviz-interest as:
               Graphviz is aborting using dot]
[Transcribed into bug report by John Ellson](gdb) run aborts.dot
Starting program: /home/ellson/FIX/Linux.x86_64/bin/dot aborts.dot
Warning: l0 was already in a rankset, ignored in cluster TripGraph
Warning: n0 was already in a rankset, ignored in cluster TripGraph
Warning: n1 was already in a rankset, ignored in cluster TripGraph
Warning: l1 was already in a rankset, ignored in cluster TripGraph
<br>

Program received signal SIGSEGV, Segmentation fault.
build_skeleton (g=0x6109f0, subg=0x625950) at cluster.c:364
364             ND_UF_size(rl)++;
(gdb) where
#0  build_skeleton (g=0x6109f0, subg=0x625950) at cluster.c:364
#1  0x00002aaaadbfe53b in class2 (g=0x6109f0) at class2.c:188
#2  0x00002aaaadc05cb8 in dot_mincross (g=0x6109f0) at mincross.c:697
#3  0x00002aaaadc032d9 in dot_layout (g=0x6109f0) at dotinit.c:227
#4  0x00002aaaaace9013 in gvLayoutJobs (gvc=Variable "gvc" is not available.

) at gvlayout.c:68
#5  0x0000000000400cdf in main (argc=Variable "argc" is not available.

) at dot.c:176
(gdb)
</CD>

**Comment by bjeanes** [comment]
Unclear if related but I have a file which `fdp` segfaults on if and only if I define a cluster. If I comment out the cluster definition or change the subgraph name to be a non-cluster, it will generate fine.

It's a big dot file but I'll see if I can get a minimal failing file.

**Comment by bjeanes** [comment]
Hmm it might have something to do with having `splines = true;` defined on the main graph actually.

**Comment by emden** [comment]
Please provide a minimal example causing the problem. Thanks.

**Comment by bjeanes** [comment]
@emden yeah I was trying in the afternoon. I have a largeish file which segfaults about 50% of the time I try to run it which I can share privately.

**Comment by emden** [comment]
Whatever works. You also might be able to anonymize the data.

**Comment by graphviz** [comment]
Ha ha you’re not going to answer Lady Arleen or whoever she was
(probably not even a woman) who threatened that if we don’t fix
or explain her problems with SVG, then, well, it won’t work for her,
and she/it/he will stamp her/its/his feet.

**Comment by emden** [comment]
I had my doubts when I first saw the name, but I checked and she is real 
and she is really trying to use Graphviz.

**Comment by bjeanes** [comment]
What?

**Comment by bjeanes** [comment]
OK apologies for the size of the dot file. I may try to find a smaller failing example later if I have the time, but in the meantime...

As can be seen, the segfault is non-deterministic so retrying a few times evokes the behaviour:

```
$ cat erd.dot | ruby anon.rb > anon.dot # anonymised version attached, still triggers issue
$ fdp -Tpdf anon.dot > /dev/null
Segmentation fault: 11
$ fdp -Tpdf anon.dot > /dev/null
$ fdp -Tpdf anon.dot > /dev/null
$ fdp -Tpdf anon.dot > /dev/null
Segmentation fault: 11
$ fdp -Tpdf anon.dot > /dev/null
$ fdp -Tpdf anon.dot > /dev/null
Segmentation fault: 11
$ fdp -Tpdf anon.dot > /dev/null
$ fdp -Tpdf anon.dot > /dev/null
Segmentation fault: 11
$ fdp -Tpdf anon.dot > /dev/null
Segmentation fault: 11
$ fdp -Tpdf anon.dot > /dev/null
```

This just in a `sh` just to have a clean environment to rule out other factors, but I was experiencing this in `zsh` (my usual shell) initially.

My anonymiser isn't perfect so there are a few artefacts of the original node names but it still triggers the segfault and is obscured enough for my own needs.

Fortunately, in my case, re-running it a few times eventually gives me a useful file so this isn't getting in my way too much at the moment.

I'm on OS X El Capitan, running 2.38.0 installed with Homebrew. Let me know if I can provide any more information.

**Comment by bjeanes** [comment]
Whoops, missed the link to the `dot` file: https://gist.github.com/bjeanes/cf6eeb49869b6c2e1f30085714fe22a5

**Comment by bjeanes** [comment]
Possibly worth noting that this file was generated automatically by [rails-erd](https://github.com/voormedia/rails-erd) and then I added `splines=true` and the cluster definitions manually. I also stripped the `weight` attributes from the nodes to get a cleaner layout with `fdp` (`rails-erd` generally assumes you're using `dot` layout), but I don't think the `weight` makes any difference to the segfault, though the `splines=true` probably does.

**Comment by jdascenzio** [comment]
Hi,
I have a similar problem on my debian 8 (dot - graphviz version 2.38.0)
I have a file 'TEST' with:
`digraph G {
	node [style=filled shape=record fillcolor=red]
	rankdir=LR
	block_01FF0005:out0 -> block_06FF0100:in0
	block_F00001FF:out0 -> block_06FF0100:in1
	block_06FF000C:out0 -> block_06FF0100:in2
	block_06FF0100 [label="{{<in0>value|<in1>period|<in2>trigger}|TEST}" fillcolor="bisque"]
	block_01FF0005:out0 -> block_06FF0012:in0
	block_06FF0011:out0 -> block_06FF0012:in1
	block_06FF0012:out2 -> block_06FF000C:in0
	block_01FF0005:out0 -> block_06FF0100:in0
}`
When I call dot -Tsvg <TEST>, I have a segfault

**Comment by magneticnorth** [comment]
Graphviz 2.38 is dated April 2014.   We may still have a bug, but this example works with graphviz 2.41 on MacOSX.
It would be nice to someday rewrite the troublesome aspects of graphviz/lib/dotgen, as soon as the funding arrives :-)

**Comment by emden** [comment]
The input jdascenzio does crash in 2.38, but the problem was fixed before graphviz-2.39.20150710.2019.

As for the input provided by bjeanes, I cannot replicate the problem even with 2.38:

+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv
+ for i in 1 2 3 4 5 6 7 8 9 10 11 12
+ /usr/local/google/home/emdenrg/graphviz-2.38.0/build/bin/fdp -Tpdf x.gv

What version of Graphviz are you using? Also can you run fdp with -v and post the trace for a failing run? Thanks.

**Comment by emden** [comment]
I'm a little confused now. First, you indicated you were getting the crashes with fdp, but the trace above is from the dot layout. Second, the trace you generated must be using your original graph, since the graph you posted has no node block_01FF0005 or port out0. Please use the anonymized graph to get a seg fault and post that grace. Thanks.

Actually, there has been a lot of cleanup since 2.38, and if we have to fix the problem, the fix will only appear in a new working release. It may be quicker for you to install 2.40 and see if the problem is still there.

**Comment by jdascenzio** [comment]
I have post a graph different from  bjeanes!
If this bug is fix in an earlier version, maybe I have to deal with debian team to fix it in debian 8...

**Comment by emden** [comment]
Sorry. I should have noticed who was posting. My final comment is definitely valid in your case. The bug you reported was in 2.38 and has been fixed, so you need to move to a new version.

**Comment by ellson** [comment]
I can't reproduce this segfault problem with the latest stable release,  graphviz-2.40.1


BTW,  I get the following warnings from your graph:


Warning: node block_01FF0005, port out0 unrecognized
Warning: node block_01FF0005, port out0 unrecognized
Warning: node block_01FF0005, port out0 unrecognized
Warning: node block_06FF0012, port in0 unrecognized
Warning: node block_F00001FF, port out0 unrecognized
Warning: node block_06FF000C, port out0 unrecognized
Warning: node block_06FF0012, port out2 unrecognized
Warning: node block_06FF000C, port in0 unrecognized
Warning: node block_06FF0011, port out0 unrecognized
Warning: node block_06FF0012, port in1 unrecognized



Generated SVG attached


John

**Comment by bjeanes** [comment]
> What version of Graphviz are you using? Also can you run fdp with -v and post the trace for a failing run? Thanks.

@emden as mentioned in my comment it looks like I was using 2.38.0. I still have that same version installed so tried again (I haven't used Graphviz much since this issue) and I can still evoke the error.

Here are two traces with `fdp -v`, one that segfaulted and one that did not (same file):

Clean:

```
sh-3.2$ fdp -v -Tpdf anon.dot > /dev/null
fdp - graphviz version 2.38.0 (20140413.2041)
Using render: quartz:quartz
Using device: pdf:quartz:quartz
libdir = "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz"
Activated plugin library: libgvplugin_neato_layout.6.dylib
Using layout: fdp:neato_layout
The plugin configuration file:
	/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/config6
		was successfully loaded.
    render	:  dot fig map pic pov ps quartz svg tk vml xdot
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot eps exr fig gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz xdot xdot1.2 xdot1.4
    loadimage	:  (lib) bmp eps gif jpe jpeg jpg pdf png ps svg
fontname: unable to resolve "Arial BoldMT"
  margin 4
pack info:
  mode   node
  size   0
  flags  0
layout Regroup
layout cluster_DE
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 16
end cluster_DE
layout cluster_workflow
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
end cluster_workflow
layout cluster_collab
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
end cluster_collab
layout cluster_auth
step size = 9
end cluster_auth
layout cluster_xport
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 17
end cluster_xport
layout cluster_accounts
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 13
end cluster_accounts
layout cluster_screening
end cluster_screening
layout cluster_QA
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 12
end cluster_QA
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
Warning: Overlap value "prism" unsupported - ignored
Adjusting ccderived+0 using Voronoi
Node separation: add=1 (4.000000,4.000000)
Number of iterations = 1
Number of increases = 0
step size = 149
end Regroup
Edge separation: add=1 (3.200000,3.200000)
Creating edges using splines
Using render: quartz:quartz
Using device: pdf:quartz:quartz
gvRenderJobs Regroup: 0.02 secs.
```

Segfault:

```
sh-3.2$ fdp -v -Tpdf anon.dot > /dev/null
fdp - graphviz version 2.38.0 (20140413.2041)
Using render: quartz:quartz
Using device: pdf:quartz:quartz
libdir = "/usr/local/Cellar/graphviz/2.38.0/lib/graphviz"
Activated plugin library: libgvplugin_neato_layout.6.dylib
Using layout: fdp:neato_layout
The plugin configuration file:
	/usr/local/Cellar/graphviz/2.38.0/lib/graphviz/config6
		was successfully loaded.
    render	:  dot fig map pic pov ps quartz svg tk vml xdot
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot eps exr fig gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz xdot xdot1.2 xdot1.4
    loadimage	:  (lib) bmp eps gif jpe jpeg jpg pdf png ps svg
fontname: unable to resolve "Arial BoldMT"
  margin 4
pack info:
  mode   node
  size   0
  flags  0
layout Regroup
layout cluster_accounts
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 14
end cluster_accounts
layout cluster_screening
end cluster_screening
layout cluster_QA
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 14
end cluster_QA
layout cluster_DE
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 19
end cluster_DE
layout cluster_workflow
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
end cluster_workflow
layout cluster_collab
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
end cluster_collab
layout cluster_auth
step size = 9
end cluster_auth
layout cluster_xport
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 22
Segmentation fault: 11
```

**Comment by jdascenzio** [comment]
I compile the version 2.40.1 (20161225.0304) on my debian and now it's work!

**Comment by bjeanes** [comment]
2.40.1 (latest installable with homebrew today) still causes the same memory address boundary error with that same file above.

Here is the output with `-v` from two segfaulting runs:

```
$ fdp -Tpdf -v anon.dot > /dev/null
fdp - graphviz version 2.40.1 (20161225.0304)
Using render: quartz:quartz
Using device: pdf:quartz:quartz
libdir = "/usr/local/Cellar/graphviz/2.40.1/lib/graphviz"
Activated plugin library: libgvplugin_neato_layout.6.dylib
Using layout: fdp:neato_layout
The plugin configuration file:
	/usr/local/Cellar/graphviz/2.40.1/lib/graphviz/config6
		was successfully loaded.
    render	:  dot dot_json fig gd json json0 map mp pic pov ps quartz svg tk vml vrml xdot xdot_json
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4 xdot_json
    loadimage	:  (lib) bmp eps gd gd2 gif jpe jpeg jpg pdf png ps svg xbm
fontname: unable to resolve "Arial BoldMT"
  margin 4
pack info:
  mode   node
  size   0
  flags  0
layout Regroup
layout cluster_accounts
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 12
Segmentation fault: 11
```

```
$ fdp -Tpdf -v anon.dot > /dev/null
fdp - graphviz version 2.40.1 (20161225.0304)
Using render: quartz:quartz
Using device: pdf:quartz:quartz
libdir = "/usr/local/Cellar/graphviz/2.40.1/lib/graphviz"
Activated plugin library: libgvplugin_neato_layout.6.dylib
Using layout: fdp:neato_layout
The plugin configuration file:
	/usr/local/Cellar/graphviz/2.40.1/lib/graphviz/config6
		was successfully loaded.
    render	:  dot dot_json fig gd json json0 map mp pic pov ps quartz svg tk vml vrml xdot xdot_json
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4 xdot_json
    loadimage	:  (lib) bmp eps gd gd2 gif jpe jpeg jpg pdf png ps svg xbm
fontname: unable to resolve "Arial BoldMT"
  margin 4
pack info:
  mode   node
  size   0
  flags  0
layout Regroup
layout cluster_accounts
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 12
end cluster_accounts
layout cluster_screening
end cluster_screening
layout cluster_QA
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 12
end cluster_QA
layout cluster_DE
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
step size = 14
end cluster_DE
layout cluster_workflow
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
end cluster_workflow
layout cluster_collab
xLayout tries = 9, mode = prism
Node separation: add=1 (4.000000,4.000000)
Segmentation fault: 11
```

As can be seen, the segfault seems to happen at different places at different times, which could also explain why it succeeds sometimes. 

Let me know if you'd like any other info. Here is some linking version info in case it's some combination of versions of dependent software:

```
/usr/local/bin/fdp:
	/usr/local/Cellar/graphviz/2.40.1/lib/libgvc.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/libtool/lib/libltdl.7.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/Cellar/graphviz/2.40.1/lib/libxdot.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/Cellar/graphviz/2.40.1/lib/libcgraph.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/Cellar/graphviz/2.40.1/lib/libpathplan.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/local/Cellar/graphviz/2.40.1/lib/libcdt.5.dylib (compatibility version 6.0.0, current version 6.0.0)
```

**Comment by emden** [comment]
I need to try this on the mac. It seems to work okay on linux.  Stephen says it is crashing in late_int, so that sounds like it might be an uninitialized variable or  bad pointer(?).

**Comment by magneticnorth** [comment]
Should I try tonight? I miss valgrind on latest macOS but it's supposedly coming.

**Comment by emden** [comment]
Actually, I ran valgrind on linux yesterday and have a pretty good idea what the problem is.

**Comment by emden** [comment]
The problem reported by bjeanes should now be fixed by revision 339add1a67aa2add550208523d9ecd73e39ba1e0. The only relevant line is 139 of fdp/layout.c.

**Comment by bjeanes** [comment]
> The problem reported by bjeanes should now be fixed by revision 339add1. The only relevant line is 139 of `fdp/layout.c`.

Confirmed. I built master locally and was not able to trigger a crash with the above file.

Thanks!
